### ISSUE TITLE
`initBlueskyComments` always returns undefined, even if no bluesky post was found

### ISSUE THREAD

**Issue by donquxiote** [czue/bluesky-comments#3]
It'd be really helpful if the `initBlueskyComments` function could return a boolean or something if it is rendering anything (like the error or loading messages). I'd like to show a placeholder if I haven't made a bluesky post yet for a specific blog post and I need some kind of indication from the function to do that.

**Comment by czue** [comment]
@donquxiote I implemented this functionality in the latest release via callback. See [the README section here](https://github.com/czue/bluesky-comments/tree/v0.5.1?tab=readme-ov-file#advanced-providing-custom-default-empty-states)

Can you let me know if that meets your needs?
